import { MaterialCommunityIcons } from "@expo/vector-icons";
import * as Clipboard from "expo-clipboard";
import { Alert, FlatList, Pressable, StyleSheet, View } from "react-native";
import { AppInputText as TextInput, AppText as Text } from "@/components/ui/Typography";
import { PrimaryButton, SecondaryButton } from "@/components/ui/Buttons";
import { ToolScreenFrame } from "@/features/tools/ToolScreenFrame";
import { colors, radius, spacing, typography } from "@/theme/tokens";
import type { ChecklistDefinition, ChecklistInstance } from "./checklistTypes";
import { checklistDisplayStatus } from "./checklistValidation";

export function ChecklistDetailScreen({ definition, instance, onArchive, onBack, onChange, onDuplicate, onNotebook }: { definition: ChecklistDefinition; instance: ChecklistInstance; onArchive: (next: ChecklistInstance) => void; onBack: () => void; onChange: (next: ChecklistInstance) => void; onDuplicate: (next: ChecklistInstance) => void; onNotebook: (text: string) => void }) {
  const items = definition.sections.flatMap((section) => section.items.map((item) => ({ ...item, section: section.title })));
  const incomplete = items.filter((item) => !instance.selectedItems.includes(item.id));
  const update = (changes: Partial<ChecklistInstance>) => onChange({ ...instance, ...changes, revision: instance.revision + 1, updatedAt: new Date().toISOString() });
  const toggle = (id: string) => update({ selectedItems: instance.selectedItems.includes(id) ? instance.selectedItems.filter((item) => item !== id) : [...instance.selectedItems, id] });
  const incompleteText = incomplete.map((item) => `- ${item.label}`).join("\n");
  return <ToolScreenFrame onBack={onBack} subtitle={`${checklistDisplayStatus(definition)} | ${definition.version}`} title={definition.title}>
    <View style={styles.meta}><Text style={styles.notice}>{definition.source}</Text><Text style={styles.metaText}>Jurisdiction: {definition.jurisdiction}</Text><Text style={styles.metaText}>Reviewed: {definition.reviewedAt} | Expires: {definition.expiresAt}</Text><Text style={styles.warning}>Confirm current legislation, police-service policy, training and supervisory direction. This checklist is an organizational aid only.</Text></View>
    <FlatList contentContainerStyle={styles.list} data={items} keyExtractor={(item) => item.id} renderItem={({ item }) => {
      const selected = instance.selectedItems.includes(item.id);
      return <Pressable accessibilityLabel={`${selected ? "Uncheck" : "Check"} ${item.label}`} accessibilityRole="checkbox" accessibilityState={{ checked: selected }} onPress={() => toggle(item.id)} style={styles.item}><MaterialCommunityIcons color={selected ? colors.ptsdGreen : colors.textMuted} name={selected ? "checkbox-marked-circle" : "checkbox-blank-circle-outline"} size={26} /><View style={{ flex: 1 }}><Text style={styles.itemText}>{item.label}</Text><Text style={styles.section}>{item.section}</Text></View></Pressable>;
    }} ListFooterComponent={<View style={styles.footer}><TextInput accessibilityLabel="Protected checklist notes" multiline onChangeText={(notes) => update({ notes })} placeholder="Protected local notes" placeholderTextColor={colors.textSubtle} style={styles.notes} value={instance.notes} /><View style={styles.row}><SecondaryButton disabled={!incompleteText} label="Copy Incomplete" onPress={() => void Clipboard.setStringAsync(incompleteText)} /><SecondaryButton disabled={!instance.notes.trim()} label="Notes to Notebook" onPress={() => { onNotebook(instance.notes.trim()); Alert.alert("Added to Notebook", "Checklist notes were copied to a protected entry."); }} /><SecondaryButton label="Reset" onPress={() => update({ completedAt: null, notes: "", selectedItems: [] })} /><SecondaryButton label="Duplicate" onPress={() => { const now = new Date().toISOString(); onDuplicate({ ...instance, archivedAt: null, completedAt: null, createdAt: now, id: `checklist-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, revision: 1, updatedAt: now }); }} /><SecondaryButton label="Archive" onPress={() => onArchive({ ...instance, archivedAt: new Date().toISOString(), revision: instance.revision + 1, updatedAt: new Date().toISOString() })} /><PrimaryButton label={incomplete.length === 0 ? "Completed" : `${incomplete.length} Remaining`} onPress={() => update({ completedAt: incomplete.length === 0 ? new Date().toISOString() : null })} /></View></View>} />
  </ToolScreenFrame>;
}

const styles = StyleSheet.create({ footer: { gap: spacing.md, paddingTop: spacing.md }, item: { alignItems: "center", backgroundColor: colors.panel, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flexDirection: "row", gap: spacing.base, minHeight: 62, padding: spacing.md }, itemText: { color: colors.textPrimary, fontSize: typography.body, fontWeight: "700" }, list: { gap: spacing.sm, padding: spacing.md }, meta: { gap: spacing.xs, padding: spacing.md }, metaText: { color: colors.textMuted, fontSize: typography.small }, notes: { backgroundColor: colors.panel, borderColor: colors.borderStrong, borderRadius: radius.lg, borderWidth: 1, color: colors.textPrimary, minHeight: 120, padding: spacing.md, textAlignVertical: "top" }, notice: { color: colors.warning, fontSize: typography.small, fontWeight: "700" }, row: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, section: { color: colors.textMuted, fontSize: typography.caption, marginTop: spacing.xs }, warning: { color: colors.textSecondary, fontSize: typography.small, lineHeight: 20, marginTop: spacing.sm } });
